# Generated by Django 3.0.5 on 2021-02-27 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='data_fim',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='municipio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='campus',
            field=models.CharField(blank=True, choices=[('AQ', 'AQ'), ('CB', 'CB'), ('CG', 'CG'), ('CX', 'CX'), ('DR', 'DR'), ('JD', 'JD'), ('NV', 'NV'), ('PP', 'PP'), ('TL', 'TL')], max_length=2),
        ),
        migrations.AlterField(
            model_name='students',
            name='curso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='idade_ate_31_12_2016',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('EAD', 'EAD'), ('PRES', 'PRESENCIAL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='nivel_do_curso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='ra',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
